### PR TITLE
Added Adm'in.2

### PR DESCRIPTION
**Pull request by viki53**
Not sure if this is worth adding, as it's not an API _per se_.

But might be helpful to some, as it's a lightweight alternative to Bootstrap (more or less)…

### CODE REVIEW

**Comment by LeaVerou** [comment]
Can you please point me to the docs that describe the HTML API? I was a bit lost with the website.

**Comment by viki53** [comment]
Sorry about that, the website is far from perfect, kind of a WIP…

Some plugins have HTML fallbacks, not all of them (yet) unfortunately.
- [Tabs](https://comin2.github.io/Adm-in.2/plugins/tabs.html)
- [Text editor](https://comin2.github.io/Adm-in.2/plugins/text-editor.html)
- [Table selector](https://comin2.github.io/Adm-in.2/plugins/table-selector.html)

With more to come, hopefully!

**Comment by LeaVerou** [comment]
Sorry for the delay, after a lot of thought I decided not to add it. The whole point of Markapp is to help people that don't know JS to find tools they can use. The website looks very confusing to a newcomer, and seems more like a work in progress (as you also point out). The internal links you provided are good, but since I cannot link directly to them, it doesn't help. :(
I’m going to go ahead and close this for now, but if in the future you happen to work on documentation, do feel free to open a new pull request.
Sorry about that, hope this doesn't put you off future contributions!

**Comment by viki53** [comment]
Hi!

No worries, I get it. I'll see if I can set some time aside to work on it and improve the docs. 😉

**Pull request closed without merging**
