### PR TITLE
Add simple RSS feed embed plugin

### PR DESCRIPTION
**Pull request by 55sketch**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi there,

Thanks for contributing. Could you please change the title to something that describes the plugin a bit better? I had to look at the demo to understand what it does.

**Comment by 55sketch** [comment]
Sure - the title of the pull request you mean? Or the name of the plugin??

**Comment by LeaVerou** [comment]
The description of the plugin in the JSON.
Btw what are the use cases for this?

**Comment by 55sketch** [comment]
Have updated the description.
The most common use case would be to embed an RSS feed on a static site, so for example my latest post from my CodePen blog

**Comment by LeaVerou** [comment]
Awesome, merged, thanks!

**Pull request merged**
