### PR TITLE
Add Vista

### PR DESCRIPTION
**Pull request by nbubna**
Library for HTML-declared, CSS-handled, location-driven control of element display. It's URL-based routing for your visuals. Fantastic for single page apps, but useful elsewhere too. Fully control what's visible with your URL #anchors or ?query=params or /the/path/itself. No javascript required.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks for contributing.
However, after reading both your message, and the Vista website, I still don't understand what this does, so I'm very skeptical that a non-programmer would have a chance to.

**Comment by nbubna** [comment]
Sheesh, i blame the guy (me) who apparently sucks at documentation. I'll have to revisit that today, i suppose.

In the meantime, a relatively simple example (when vista is included at page load) is like so:

```
<div vista="foo">
  Foo! <!-- gets hidden until (location.href.match('foo') !== null) -->
</div>
<div vista="!foo">
 Bar. <!-- is visible as long as (location.href.match('foo') === null) -->
</div>
<a href="#shows-foo">Clicking this will show Foo and hide Bar</a>
<a href="#whatever">Clicking this will hide Foo and show Bar</a>
```

It allows single page applications declarative control what elements are or aren't displayed based on the URL. It writes custom CSS rules to make it work and make it very fast.

**Comment by LeaVerou** [comment]
That's super useful! But yeah, it needs better documentation and more examples to have any chance to be understood by non-developers. Currently the docs suffer from the curse of knowledge: You intimately know how this library works, so the docs are written for other people who also understand what this is about and just need a reminder.

E.g. you use "test" a lot, but the documentation on defining these tests is not quite understandable. What are these tests? Are they defined via a `<meta>` or can they also be defined inline in the vista attribute? If the user doesn't speak regexp, can they still define a useful test? The most common cases of tests are probably:
- Does URL param foo have the value bar?
- Is the hash equal to foo? (not just contains foo)

Can these be defined without regexp knowledge?

In general, examples, examples, examples. Humans are pattern matching creatures. Examples are much more easily understood than theoretical prose (of course both is even better).

**Comment by nbubna** [comment]
Ok, i've revamped the docs, trying to make less assumptions. I did, as you guessed, write them for internal use at first.  They now have better explanations, definitions, and examples.

Tests, are the URL tests run when a URL change is detected. I think that is better explained now. They can be implicit when defined inline, or explicit via `<meta>` or JavaScript definitions. I'll update the examples to cover your two common cases. And no, definitely no regexp knowledge necessary for basic use, but it sure comes in handy if you need to be really picky about URL matching. In general, though, i've found that i rarely use regexp test definitions.

**Comment by nbubna** [comment]
Lea, i went through it again tonight. I'm fairly satisfied with the documentation at this point. Any more feedback is welcome. Hope this is satisfactory for inclusion! I've been heavily and happily using iterations of this codebase in my projects for years now. While i realize it is a bit unorthodox in its approach, i do think (hope, at least) that others should find it useful and user-friendly.

**Comment by LeaVerou** [comment]
Thanks for improving the docs, they are indeed better now. I've merged this.

However, unrelated to this listing, I still find that the docs are written with JS developers in mind. People who don't understand JS don't know what `loaction.href.match()` means, or even what `location.href` is. They don't know what `RegExp` or `Function` is either. I would also suggest you add some sort of shortcut for easily matching search params (e.g. the `layout=grid` example). Having to use a regexp for something so common is a bit counterintuitive.

But great project idea overall!

**Comment by nbubna** [comment]
Sure, i can make things less JS-centric. And honestly, you don't have to use regexp for a search param, setting your test as merely "layout=grid" works fine. It just isn't exact.

Adding a shortcut for search params would mean either an alternate attribute or alternate syntax for the test. I'll have to think on that.

Thanks for the include and the great feedback!

**Comment by LeaVerou** [comment]
> It just isn't exact

Yup, it isn't exact for both the param name and the value, which could lead to very weird bugs.

**Comment by nbubna** [comment]
I've been toying with ideas for special syntax for params. Thus far, it's been unsatisfying.

Then it occurred to me that perhaps the issue is that all simple tests default to being, well, inexact. I can't think of a case where i explicitly want that; it was just the easy implementation. It seems now that it might be prudent to prefix and postfix all simple tests with a boundary (e.g. "layout=grid" becomes "\blayout=grid\b").

Wouldn't that honor the principle of least surprise best? Should anyone actually want to ignore word boundaries when matching to URLs, wouldn't that be a fairly advanced use, therefore justifying a regexp?

**Comment by LeaVerou** [comment]
Possibly, but keep in mind that this still does not prevent false matches. `foo=bar` will still match `yolo-foo=bar-yolo`

**Comment by nbubna** [comment]
True, though it does dramatically reduce the problem. Hmm, i think using URL-specific boundaries ought to reduce false matches far more still. How about: 

`"layout=grid"` to `"(^|/|\\?|=|&|#)layout=grid($|/|\\?|=|&|#)"`

You've not yet failed to catch the flaws in my thinking thus far; am i still missing some obvious case?

**Comment by LeaVerou** [comment]
I think that makes sense!

**Pull request merged**
