### PR TITLE
Adds addel

### PR DESCRIPTION
**Pull request by kobykorman**

### CODE REVIEW

**Comment by LeaVerou** [comment]
This seems to require JS for initialization?

**Comment by kobykorman** [comment]
My bad, I missed: 

> Every time you require JS code to **initialise** or configure your UI library you are excluding them.

Right now you need to call `$('#whatever').addel()` to init.
If init is done automatically, on, let's say, elements that have `data-addel-container`, it'd be satisfactory, correct?

Edit: I saw Bootstrap included, and they have this in their docs:

> For performance reasons, the Tooltip and Popover data-apis are opt-in, meaning you must initialize them yourself.

**Comment by LeaVerou** [comment]
> If init is done automatically, on, let's say, elements that have data-addel-container, it'd be satisfactory, correct?

Yes.

> I saw Bootstrap included, and they have this in their docs:
> 
> > For performance reasons, the Tooltip and Popover data-apis are opt-in, meaning you must initialize them yourself.

By "initialize them yourself" they mean with JS? That's unfortunate, but Bootstrap still has a lot of stuff that can be used from HTML, and it was among the first to have HTML APIs when every other library required JS.

**Comment by kobykorman** [comment]
Ok, I'll update here when I release a new version that satisfies that requirement, thanks.

Yeah, they do. Don't get me wrong, I'm a big BS fan, I was just wondering about that bit.

**Comment by LeaVerou** [comment]
Doing some housekeeping around here, so gotta close this.
Feel free to open it or open a new PR if you release a new version that satisfies that requirement!

**Pull request closed without merging**
