### PR TITLE
add Daniel-Hug/tabbed-panels

### PR DESCRIPTION
**Pull request by Daniel-Hug**

### CODE REVIEW

**Comment by LeaVerou** [comment]
I think it's best to point people to the README, since the main website seems to be just a demo. I was a bit lost before I tried going to the repo.

**Comment by Daniel-Hug** [comment]
Thanks! Fixed.

**Comment by LeaVerou** [comment]
Ahem, now it has merge conflicts... :/

**Comment by Daniel-Hug** [comment]
Good now. Thanks!

**Comment by LeaVerou** [comment]
Merged, thanks!

I would suggest you make a website for this. It's a nice little library, and it would be more popular with some proper documentation & demos.

**Pull request merged**
