### PR TITLE
Add BunnyJS

### PR DESCRIPTION
**Pull request by Mevrael**
Thx Lea, very nice idea to gather simple libraries with humane HTML syntax.

P.S. My favorite commit message "Damn Safari I hate you". Even IE is better :<

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks for contributing! However, it looks like this is a collection of libraries. While it's a great idea, I think it would be best to add the individual libraries (if they have an HTML API).

If you send a new PR for them, please add them so that the list is still alphabetical :)

**Comment by Mevrael** [comment]
Hi @LeaVerou 

Yes, you can call it a collection, however, it is a single package and called a framework. Same as Bootstrap framework which is already added https://github.com/LeaVerou/markapp/pull/7

It is not an option to add over 9000 rows.

BunnyJS UI components has HTML API. For example, native HTML5 form validation - https://bunnyjs.com/examples/form-validation/

P.S. I would recommend to organize your list, at least by adding a categories or tags.

**Comment by LeaVerou** [comment]
I don't think you understand what an HTML API is. A library that includes an HTML API is usable without writing a single line of Javascript. Please do not send pull requests to repos without reading their CONTRIBUTING.md first.

**Comment by Mevrael** [comment]
@LeaVerou 

So, if you tell me that I don't read contribution guidelines and don't understand a sentence, let's play a lawyer, as you wish.

You have this library in your list:

http://packery.metafizzy.co/#initialize-in-html

Which is initialized that way:

`<div class="grid" data-packery='{ "itemSelector": ".grid-item", "gutter": 10 }'>`

It is called JSON - in simple words JavaScript object. It is a one line of JavaScript right in the HTML attribute. Unfortunately this doesn't fit your HTML API definition.

So what I see - author defines the definition himself and will always change the meaning of the term in every situation in one's favor.

Now, let me explain, why you need to write a one very short line of JavaScript in my Form validation: `Validate.init(formElement)`. I was thinking about adding some kind of init-attribute but I am still not sure that adding DOMContentLoaded directly in the component is a good option in that case because in modern world you still have to write a business (controller) logic. It's not enough to validate a form, you have to define what should happen next.

Finally, as I said BunnyJS is a framework and a set of many components united by the same philosophy, software engineering principles and architecture. Here are examples where you can see DOMContentLoaded at the bottom of the files:
https://github.com/Mevrael/bunny/blob/master/src/TabSection.js
https://github.com/Mevrael/bunny/blob/master/src/Dropdown.js
https://github.com/Mevrael/bunny/blob/master/src/DynamicInput.js

So, as we can see BunnyJS matches your definition of HTML API.

P.S. I also wouldn't call initialization via class an HTML API. This is also a bad practice to use CSS class that way. You already have a couple of libraries in your list which added "initialization classes". In some situations CSS classes can be automatically removed in real projects if they don't have any styling. In any case classes should be used only for styles.

**Comment by LeaVerou** [comment]
Feel free to open a new PR about removing Packery from the list. If a library without an HTML API has been erroneously added, that would be the right course of action, not adding more.

I don't understand what your point is. This is a list of libraries with HTML APIs, and you seem to be arguing against the whole idea of the list. Then why do you want your library added to it? And what exactly do you want the list to become, just a random assortment of libraries? What's the point then?

>  In any case classes should be used only for styles.

Says who? They're not "CSS classes", they're classes. Nothing in the HTML spec restricts them to CSS. If somebody automatically removes a class because it's not used in the CSS, they're bad at their job.

> I was thinking about adding some kind of init-attribute but I am still not sure that adding DOMContentLoaded directly in the component is a good option in that case because in modern world you still have to write a business (controller) logic.

Ahem, the people that benefit the most out of an HTML API have no clue what a controller even is.

**Comment by Mevrael** [comment]
> Says who? They're not "CSS classes", they're classes. Nothing in the HTML spec restricts them to CSS. If somebody automatically removes a class because it's not used in the CSS, they're bad at their job.

If somebody is not using right tool for the right job, he will be fired.

CSS was invented to separate markup from styling. In previous HTML specifications it was clearly defined that classes, CSS code is for styling purposes.

Below are just some of the links explaining why targeting classes with JS is a bad practice.
- http://roytomeij.com/blog/2012/dont-use-class-names-to-find-HTML-elements-with-JS.html
- https://toddmotto.com/data-js-selectors-enhancing-html5-development-by-separating-css-from-javascript/
- https://intuio.at/blog/dont-use-data-attributes-to-find-html-elements-with-js/
- https://www.sitepoint.com/web-foundations/class-html-attribute/

This is also mine own, experienced web app architect's, recommendation. Otherwise, you might have conflicts and side effects because of 3rd party code which added an unexpected behaviour to your existing architecture and codebase.

Using at least data- attributes or today It's common to use custom tags and attributes. Also when you see in the HTML `<div class="red" super-carousel>` or even `<supercarousel>` you instantly understand what code is doing while by looking on `class="one two three four five over9000"` you can't tell what it does. I'm not working on Chrome, Firefox, Edge and can't tell you that adding even an empty class wouldn't do a repaint. Nevertheless, if there is no other option I always recommend to my students and employees to add `js-` prefix to classes.

You can also make your own suggestions and recommendations about this topic, and I would like to hear anything, if there is a better approach, however, with Web Components coming, we will be just importing HTML with custom JS anyway.

> Says who?

Same I would like to ask about "HTML API". Where I can find the definition of it? What is HTML API? What I see is only your own thoughts.

> Ahem, the people that benefit the most out of an HTML API have no clue what a controller even is.

Can you provide some links to the articles, discussions or any research done by people using HTML API?

P.S. front-end engineer who don't know what controller is, is not a front-end engineer.

> Then why do you want your library added to it?

Because it fits your "HTML API" definition. It also is one of core principles of BunnyJS - simplicity in using and extending. Let's look again on [Dropdown](https://github.com/Mevrael/bunny/blob/master/src/Dropdown.js) component which is a Vanilla JS implementation for [Bootstrap 3/4 Dropdowns.](http://v4-alpha.getbootstrap.com/components/dropdowns/).

You can open DevTools on https://bunnyjs.com and will see that there is only dropdown.min.js included.

**Comment by LeaVerou** [comment]
> P.S. front-end engineer who don't know what controller is, is not a front-end engineer.

Sure, but it's not only engineers who put stuff on the Web, nor should they be the only ones. What about web designers, or even hobbyists?

**Pull request closed without merging**
