### PR TITLE
Proposed togglr

### PR DESCRIPTION
**Pull request by stefanoio**
togglr let's you easily create actions for adding, removing, and toggling classes on user input without writing a single line of js.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks. The description should describe what it does though. "The super lightweight zero dependencies useful utility" does not.

**Comment by stefanoio** [comment]
Hi, I've pushed a more descriptive description of what it does.

**Comment by LeaVerou** [comment]
Thanks, merged!

**Comment by stefanoio** [comment]
Thank you!

**Pull request merged**
