### PR TITLE
Add fotorama.io

### PR DESCRIPTION
**Pull request by laviperchik**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Fantastic, perfect fit! Thank you!
Please fix the merge conflicts and put it in the correct alphabetical position?

**Comment by LeaVerou** [comment]
Still has merge conflicts…

**Comment by laviperchik** [comment]
Ok, fixed it!

**Comment by LeaVerou** [comment]
Yay, thanks!

**Comment by laviperchik** [comment]
Oh shoot, it's in the wrong order :(

**Comment by LeaVerou** [comment]
New PR?

**Comment by laviperchik** [comment]
Yep, I'm done now.

**Pull request merged**
