### PR TITLE
add Daniel-Hug/speech-input

### PR DESCRIPTION
**Pull request by Daniel-Hug**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Nice, but same advice applies: The main website doesn't make sense by itself, so it would be better to point to the readme.

Btw:

> Wrap the input in a <div> with an si-wrapper class.
> Add a button with an si-btn class as a sibling to the input. For the default style use the button markup in the example below:

Your script could do this to elements that have the .si-input class. This kind of repetitive grunt work is suited to machines, not humans. It also reduces error conditions as people can now add the `si-input` class without doing any of that.

**Comment by Daniel-Hug** [comment]
Both suggestions implemented.

**Comment by LeaVerou** [comment]
Thanks!

Wait a second, if this only works in WebKit, what's the advantage over the `x-webkit-speech` attribute?

**Comment by Daniel-Hug** [comment]
From my most recent testing [here](http://codepen.io/matt-west/full/wbpqu), the `x-webkit-speech` attribute is no longer supported in at least Chrome.

**Comment by LeaVerou** [comment]
Is the specification on any standards track? I'm a bit hesitant to encourage nonstandard APIs...

**Comment by Daniel-Hug** [comment]
The speech-input module I've made works off an `<input class="speech-input">` rather than an `<input x-webkit-speech>`.

The web speech API in use can be enabled in FF and is in development in Edge: http://caniuse.com/#feat=speech-recognition

**Comment by Daniel-Hug** [comment]
Actually, it looks like FF only supports synthesis not recognition yet: https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API#Browser_compatibility

**Comment by LeaVerou** [comment]
Sorry for the delay, after a lot of thought I decided not to add it. The whole point of Markapp is to help people that don't know JS to find tools they can use. While this tool has a nice HTML API, it’s WebKit-only, and based on a technology that does not even appear to be on a standards track (the spec is from a Community Group). Furthermore, even though this PR has been open for over a year, it looks like the support landscape hasn't changed.

I’m going to go ahead and close this for now, but if in the future the situation changes, do feel free to open a new pull request.
Sorry about that, hope this doesn't put you off future contributions!

**Pull request closed without merging**
